"""initial schema

Revision ID: bbd5a2b91492
Revises: 
Create Date: 2025-08-05 01:25:14.436296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd5a2b91492'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not sa.inspect(op.get_bind()).has_table("estoques_local"):
        op.create_table('estoques_local',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('codigo', sa.String(length=20), nullable=False),
        sa.Column('localizacao', sa.String(length=200), nullable=False),
        sa.Column('prateleira', sa.String(length=50), nullable=True),
        sa.Column('coluna', sa.String(length=50), nullable=True),
        sa.Column('setor', sa.String(length=100), nullable=True),
        sa.Column('responsavel', sa.String(length=100), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codigo'),
        sa.UniqueConstraint('nome')
        )
    if not sa.inspect(op.get_bind()).has_table("grupos_item"):
        op.create_table('grupos_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('codigo', sa.String(length=20), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codigo'),
        sa.UniqueConstraint('nome')
        )
    op.create_table('mecanicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('nivel_experiencia', sa.String(length=20), nullable=False),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('tipos_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor_identificacao', sa.String(length=7), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('nivel_acesso', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_equipamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('fabricante', sa.String(length=50), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=False),
    sa.Column('horimetro_atual', sa.Float(), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=False),
    sa.Column('valor_aquisicao', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_equipamento_id'], ['tipos_equipamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grupo_item_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('min_estoque', sa.Integer(), nullable=True),
    sa.Column('max_estoque', sa.Integer(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=True),
    sa.Column('ultimo_preco_avaliacao', sa.Float(), nullable=True),
    sa.Column('ultimo_preco_compra', sa.Float(), nullable=True),
    sa.Column('estoque_local_id', sa.Integer(), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('fornecedor', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ultima_inventariacao_data', sa.DateTime(), nullable=True),
    sa.Column('ultima_inventariacao_usuario', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_local_id'], ['estoques_local.id'], ),
    sa.ForeignKeyConstraint(['grupo_item_id'], ['grupos_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('analises_oleo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('numero_amostra', sa.String(length=50), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('horimetro_coleta', sa.Float(), nullable=True),
    sa.Column('tipo_oleo', sa.String(length=100), nullable=False),
    sa.Column('laboratorio', sa.String(length=100), nullable=True),
    sa.Column('data_resultado_lab', sa.DateTime(), nullable=True),
    sa.Column('parametros_analisados', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratativa_recomendada', sa.Text(), nullable=True),
    sa.Column('tratativa_executada', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('responsavel_coleta', sa.String(length=100), nullable=True),
    sa.Column('responsavel_analise', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_amostra')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_os', sa.String(length=50), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_manutencao_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('descricao_problema', sa.Text(), nullable=False),
    sa.Column('descricao_solucao', sa.Text(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_encerramento', sa.DateTime(), nullable=True),
    sa.Column('tempo_execucao_horas', sa.Float(), nullable=True),
    sa.Column('custo_mao_obra', sa.Float(), nullable=True),
    sa.Column('custo_pecas', sa.Float(), nullable=True),
    sa.Column('custo_total', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('assinatura_responsavel', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanicos.id'], ),
    sa.ForeignKeyConstraint(['tipo_manutencao_id'], ['tipos_manutencao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_os')
    )
    op.create_table('planos_preventiva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_manutencao_id', sa.Integer(), nullable=False),
    sa.Column('intervalo_horas', sa.Integer(), nullable=True),
    sa.Column('intervalo_dias', sa.Integer(), nullable=True),
    sa.Column('intervalo_km', sa.Float(), nullable=True),
    sa.Column('antecedencia_dias', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultima_execucao_data', sa.DateTime(), nullable=True),
    sa.Column('ultima_execucao_horimetro', sa.Float(), nullable=True),
    sa.Column('ultima_execucao_km', sa.Float(), nullable=True),
    sa.Column('proxima_execucao_data', sa.DateTime(), nullable=True),
    sa.Column('proxima_execucao_horimetro', sa.Float(), nullable=True),
    sa.Column('proxima_execucao_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['tipo_manutencao_id'], ['tipos_manutencao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pneus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=50), nullable=False),
    sa.Column('numero_fogo', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('medida', sa.String(length=30), nullable=False),
    sa.Column('medida_sulco_mm', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('posicao', sa.String(length=20), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('valor_compra', sa.Float(), nullable=True),
    sa.Column('data_instalacao', sa.Date(), nullable=True),
    sa.Column('km_instalacao', sa.Float(), nullable=True),
    sa.Column('km_atual', sa.Float(), nullable=True),
    sa.Column('pressao_recomendada', sa.Float(), nullable=True),
    sa.Column('vida_util_estimada', sa.Float(), nullable=True),
    sa.Column('fornecedor', sa.String(length=100), nullable=True),
    sa.Column('fornecedor_recapagem', sa.String(length=100), nullable=True),
    sa.Column('data_recapagem', sa.Date(), nullable=True),
    sa.Column('data_descarte', sa.Date(), nullable=True),
    sa.Column('motivo_descarte', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('backlog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('urgencia', sa.String(length=20), nullable=True),
    sa.Column('impacto', sa.String(length=20), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('plano_preventiva_id', sa.Integer(), nullable=True),
    sa.Column('esforco_estimado', sa.Float(), nullable=True),
    sa.Column('custo_estimado', sa.Float(), nullable=True),
    sa.Column('data_identificacao', sa.DateTime(), nullable=True),
    sa.Column('data_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('score_priorizacao', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['plano_preventiva_id'], ['planos_preventiva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('numero_nf', sa.String(length=50), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('estoque_origem_id', sa.Integer(), nullable=True),
    sa.Column('estoque_destino_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['estoque_destino_id'], ['estoques_local.id'], ),
    sa.ForeignKeyConstraint(['estoque_origem_id'], ['estoques_local.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanicos.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('os_pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_utilizada', sa.Integer(), nullable=False),
    sa.Column('custo_unitario_na_epoca', sa.Float(), nullable=True),
    sa.Column('custo_total', sa.Float(), nullable=True),
    sa.Column('data_utilizacao', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('os_pecas')
    op.drop_table('movimentacoes_estoque')
    op.drop_table('backlog_items')
    op.drop_table('pneus')
    op.drop_table('planos_preventiva')
    op.drop_table('ordens_servico')
    op.drop_table('analises_oleo')
    op.drop_table('pecas')
    op.drop_table('equipamentos')
    op.drop_table('usuarios')
    op.drop_table('tipos_manutencao')
    op.drop_table('tipos_equipamento')
    op.drop_table('mecanicos')
    op.drop_table('grupos_item')
    op.drop_table('estoques_local')
    # ### end Alembic commands ###
