"""create tabela itens

Revision ID: c88aaf0732bc
Revises: e5963818dfc8
Create Date: 2025-08-05 21:11:44.710822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'c88aaf0732bc'
down_revision: Union[str, Sequence[str], None] = 'e5963818dfc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    if not inspector.has_table('itens'):
        op.create_table('itens',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('numero_item', sa.String(length=50), nullable=False),
            sa.Column('descricao_item', sa.Text(), nullable=False),
            sa.Column('grupo_itens', sa.String(length=100), nullable=True),
            sa.Column('unidade_medida', sa.String(length=20), nullable=True),
            sa.Column('ultimo_preco_avaliacao', sa.Numeric(precision=12, scale=2), nullable=True),
            sa.Column('ultimo_preco_compra', sa.Numeric(precision=12, scale=2), nullable=True),
            sa.Column('estoque_baixo', sa.Boolean(), nullable=True),
            sa.Column('data_registro', sa.TIMESTAMP(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('numero_item')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    if inspector.has_table('itens'):
        op.drop_table('itens')
    # ### end Alembic commands ###
